port: 10211
log:
  level: debug
  reqRes: false
security:
  jwtSecret: asdlk4pc-p2
postgres:
  underscored: true
  host: localhost
  dialect: postgres
  database: database_development
  username: postgres
  password: postgres
  pool:
    max: 10
    min: 0
    acquire: 30000
    idle: 10000