version: '3.7'
services:
  postgres:
    image: postgres:10.6
    restart: always
    ports:
     - "5432:5432"
    volumes:
         - pgdata:/var/lib/postgresql/dataoc
    # this environment variable - as noted on Docker Hub - will
    # create a database with this name if it doesnt already exist
    # when we start out container
    environment:
      POSTGRES_DB: database_anyvision_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
    - my-network
  migrate:
    image: anyvision-server
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    command: npm run createDb
    working_dir: /usr/src/app
    networks:
    - my-network
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
  anyvision:
    image: anyvision-server
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    command: npm run start
    # volumes:
    #   - .:/usr/src/app
    #   # - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "10211:10211"
      - "9229:9229"
    networks:
    - my-network
    depends_on:
      - postgres
volumes: 
     pgdata:
networks:
  my-network:
    driver: bridge