const SIGN_UP = "SIGN_UP";
const LOGIN = "LOGIN";
const AUTH_COMPLETED = "AUTH_COMPLETED";
const ADD_NEW_URL = 'ADD_NEW_URL';
const ADD_NEW_URL_SUCCESS = 'ADD_NEW_URL_SUCCESS';

export default {
  SIGN_UP,
  AUTH_COMPLETED,
  LOGIN,
  ADD_NEW_URL,
  ADD_NEW_URL_SUCCESS,
};
